@startuml US1002_SSD

autonumber
title: US1002 - Register a Job Opening

actor CustomerManager as "Customer Manager"

activate CustomerManager

CustomerManager -> ":System" : asks the system to create a new Job Opening
activate ":System"

":System" --> CustomerManager : requests data (title, address, description, contractType, numberOfVacancies, mode, company)
deactivate ":System"

CustomerManager -> ":System" : types request data
activate ":System"

":System" --> CustomerManager : requests confirmation
deactivate ":System"

CustomerManager -> ":System" : confirms the data
activate ":System"
":System" --> CustomerManager : informs operation success
deactivate ":System"

deactivate CustomerManager

@enduml